fiona/ogrext.pyx
=> remove read ts

fiona/__init__.py, fiona/_drivers.pyx, fiona/collection.py, fiona/errors.py, fiona/ograpi.pxd, fiona/ogrext.pyx, tests/test_drivers.py, tests/test_read_drivers.py
Closes issue #192.
See test_read_drivers.py for examples. Documentation forthcoming.
=> Control over drivers when opening datasets to read.

README.rst, setup.py
Share the enhancement to setup.py that rasterio recently gained.
=> Enhancements to setup.py

fiona/_geometry.pxd, requirements-dev.txt
Completely based on the work by brendan-ward for rasterio
https://github.com/mapbox/rasterio/pull/373/files
Changes were needed to build on debian unstable.
Resolves #214
=> Fix compatibility with Cython 0.22

fiona/fio/info.py
@sgillies this is a critical bug for v1.6.
During the CLI shuffle to support cligj's plugin implementation I omitted an `import fiona.crs` in `fiona/fio/info.py`.  There are a few `fio-info` tests in `tests/test_cli.py` but I have no idea why they don't fail.
- Running `fio info tests/data/coutwildrnp.shp` in master demonstrates the problem.
- `py.test` shows that 4 tests in `tests/test_cli.py` run and pass.
- Running `py.test tests/test_cli.py` shows that 3 tests fail, which is what should be happening.
- Executing the tests independently with `py.test tests/test_cli.py::test_info_json` (etc) also causes the tests to fail.
- I verified that the tests are actually running when doing `py.test tests` by adding an `assert False` to one of them. 
Maybe a `py.test` bug?  Regardless, adding the …
=> fio-info bug fix

fiona/fio/main.py, setup.py
=> Use click-plugins instead of cligj.plugins.  Closes #243.

fiona/fio/info.py
Closes #249.
@sgillies ready for review.
=> Add boilerplate for additional interpreters in 'fio insp' and implement IPython support.

fiona/ogrext.pyx, tests/test_props.py
Closes #256 
@sgillies Ready for review.
=> Only deserialize JSON properties when using the GeoJSON driver

CHANGES.txt, fiona/__init__.py, fiona/collection.py, fiona/ogrext.pyx, tests/test_bytescollection.py, tests/test_collection.py, tests/test_collection_crs.py, tests/test_profile.py
Replaces #269, which had the wrong base branch.
=> Add crs_wkt to meta property

README.rst, fiona/ogrext2.pyx
=> Just use int as a plain old builtin

fiona/errors.py, fiona/ogrext.pyx, tests/test_unicode.py
=> Prevent sending undefined or non-UTF strings into OGR

setup.py
The clean target should modify these files, it prevents builds of the Debian package due to unexpected changes to the source.
=> Don't copy gdalapi & data files in clean target.

CHANGES.txt, fiona/__init__.py
And add a `__gdal_version__` attribute.
=> Raise ImportError on GDAL version mismatch.

.travis.yml, fiona/errors.py, fiona/ograpi.pxd, fiona/ogrext.pyx, requirements-dev.txt, tests/test_unicode.py
Resolves #356
Also add a test for simplified Chinese encoding support and another test to highlight OGR's silent encoding failure issue.
=> Fix unicode error handling

.travis.yml, fiona/collection.py, tests/test_collection.py
=> Add a profile property

setup.py
See: https://github.com/Toblerity/Fiona/pull/362#issuecomment-226233190
=> Fix undefined ext_modules introduced via #362

setup.py
=> GDAL_VERSION configures gdalversion

tests/test_collection.py
https://github.com/Toblerity/Fiona/issues/391
=> Update tests for Windows.

fiona/_geometry.pxd, fiona/_geometry.pyx, fiona/ogrext1.pyx, fiona/ogrext2.pyx, tests/test_collection.py, tests/test_geometry.py, tests/test_schema.py
I've added two new functions to fiona._geometry to make the type handling more robust.
=> Resolves #340

CHANGES.txt, fiona/__init__.py, fiona/ogrext1.pyx, fiona/ogrext2.pyx, tests/test_collection.py
=> Added support for layer creation options and a test.

fiona/collection.py, fiona/ogrext1.pyx, fiona/ogrext2.pyx, tests/test_bytescollection.py, tests/test_collection.py, tests/test_drivers.py, tests/test_feature.py, tests/test_geojson.py, tests/test_geometry.py, tests/test_geopackage.py, tests/test_layer.py, tests/test_listing.py, tests/test_multiconxn.py, tests/test_read_drivers.py, tests/test_remove.py, tests/test_revolvingdoor.py, tests/test_rfc3339.py, tests/test_slice.py, tests/test_unicode.py, tests/test_vfs.py
=> Add extension to VSI filenames so we can access zipped bytes

tests/test_fio_cat.py
this fixes for me the test on appveyor. Let's see if it really works.
See https://github.com/Toblerity/Fiona/issues/414
=> Fixappveyor

CHANGES.txt, fiona/__init__.py, fiona/ogrext2.pxd, fiona/ogrext2.pyx
Replace our own faulty method with GDAL's tried and true method. Less code! A follow up to #428.
=> Use cpl_string functions instead of our own string_list

.travis.yml, fiona/__init__.py, fiona/_err.pxd, fiona/_err.pyx, fiona/collection.py, fiona/compat.py, fiona/errors.py, fiona/ogrext1.pyx, fiona/ogrext2.pyx, setup.py, tests/test_geojson.py
=> Context errors

.travis.yml, fiona/ogrext1.pyx, fiona/ogrext2.pxd, fiona/ogrext2.pyx, setup.py, tests/test_bytescollection.py, tests/test_collection.py, tests/test_drivers.py, tests/test_feature.py
Released yesterday: http://download.osgeo.org/gdal/2.2.0/
=> Add GDAL 2.2.0 to Travis build matrix

.travis.yml, fiona/ogrext1.pyx, fiona/ogrext2.pxd, fiona/ogrext2.pyx, setup.py, tests/test_bytescollection.py, tests/test_collection.py, tests/test_drivers.py, tests/test_feature.py
=> Revert "Add GDAL 2.2.0 to Travis build matrix"

CHANGES.txt, fiona/fio/options.py
=> Remove unintended output in fio cat

environment.yml, readthedocs.yml
I added the simplest environment possible to build the docs on Read the Docs. You can see the result here:
http://juanlu001-fiona.readthedocs.io/
Fixes #258.
=> Build docs on Read the Docs

docs/manual.rst
add a note about precision models being a potential source of getting data dirty in fiona
=> precision models can dirty data

tests/test_collection.py, tests/test_drivers.py, tests/test_geopackage.py
This PR fixes a few outstanding warnings in the tests.
Appveyor failure is fixed in another PR.
=> Fix some warnings in tests

tests/test_collection.py
=> Add some unit tests on number formatting (#528)

ISSUE_TEMPLATE.md
I think it would be useful to ask users to submit their GDAL version in new issues.
=> Request GDAL version information in issue template

fiona/fio/cat.py, tests/test_fio_cat.py
=> Fix fio cat with bbox when using more than one file

fiona/_err.pyx, fiona/_shim1.pxd, fiona/_shim1.pyx, fiona/_shim2.pxd, fiona/_shim2.pyx, fiona/_shim22.pxd, fiona/_shim22.pyx, fiona/ogrext.pyx, fiona/ogrext1.pxd, fiona/ogrext2.pxd, tests/test_collection.py, tests/test_geojson.py, tests/test_geopackage.py, tests/test_listing.py
This is another attempt at #532. I think it's ready for review and merge (if everything looks OK).
Some of the assumptions will need revisiting when we support writing to VFS (see #508).
Closes #438.
Closes #515.
=> Refactor of error handling when opening files

CHANGES.txt, fiona/_geometry.pyx, tests/test_collection.py
=> Do not collapse Z and M types to 2D

appveyor.yml
Still not touching Python 2.7 for now.
=> Update to python 3.6.4 and GDAL 2.2.3

scripts/travis_gdal_install.sh
change clone of gdal trunk to master, as the trunk branch does not exist anymore
=> change branch name to master

tests/test_drivers.py
=> Fix for GDAL 1.x in test_drivers.py::test_options

.gitignore, appveyor.yml, fiona/__init__.py, requirements-dev.txt, setup.py
Trying to build a wheels for Windows using the gisinternals libraries on Appveyor. Submitting this PR to trigger the Appveyor builds.
=> Build wheel artifact on Appveyor

CHANGES.txt, fiona/_drivers.pyx
I'm adding Debian's locations to the default search paths and am using `CPLSetConfigOption` instead of modifying the process environment (`os.environ`).
Resolves #583
=> GDAL_DATA improvements

fiona/fio/load.py, tests/test_fio_load.py
=> Use features_in_arg from cligj in fiona/fio/load.py

docs/manual.rst
Finally integrated fixes from the comments :)
edit: pfff, this new PR comment overwrote any introductory comment I had up here before (not sure if I did)...
=> Docs file from scratch

.travis.yml
=> Added GDAL 2.3.0 to the Travis build matrix

requirements.txt, tests/test_vfs.py
=> Added click-plugins to requirements.txt

fiona/__init__.py, fiona/compat.py, fiona/env.py, fiona/errors.py, fiona/fio/env.py, fiona/ogrext.pyx, tests/conftest.py, tests/test_vfs.py
=> Remove env cruft, add env tests

tests/test_geometry.py
Make the round-tripping ones into two tests with parametrization and flatten the wkb tests without the class. Remove a bit of code duplication too with the hex-to-bytes bit.
=> Remove unittest from geometry tests

tests/conftest.py, tests/test_drivers.py, tests/test_logutils.py, tests/test_read_drivers.py
Also fix the `data_dir` fixture to work if you're already in the `tests` directory.
=> Use path fixtures in more tests

tests/test_layer.py, tests/test_vfs.py
I don't yet want to touch `test_collection`, but this is the first step.
=> Use bare assert in ReadingTest subclasses.

tests/__init__.py, tests/test_bytescollection.py, tests/test_collection.py, tests/test_layer.py, tests/test_vfs.py
With #654, this means there's no more unittest.
=> Drop unittest from collection tests

CHANGES.txt, fiona/__init__.py, fiona/ogrext.pyx, tests/test_collection.py
=> Eliminate log messages about ENCODING

setup.py
=> Set cython language_level=3

fiona/_drivers.pyx, fiona/_env.pyx, fiona/_geometry.pxd, fiona/_geometry.pyx, fiona/_shim1.pxd, fiona/_shim2.pxd, fiona/_shim2.pyx, fiona/_shim22.pxd, fiona/_shim22.pyx, fiona/ogrext.pyx, fiona/ogrext1.pxd, fiona/ogrext2.pxd, setup.py
Some type improvements, reducing the number of warnings at compile time.
The handling of the `OGRFieldSubType` enum isn't quite right but doesn't cause any errors.
=> Some type improvements

fiona/__init__.py, fiona/_env.pyx, fiona/_err.pyx, fiona/collection.py, fiona/env.py, fiona/ogrext.pyx, tests/test_bigint.py, tests/test_collection.py, tests/test_env.py, tests/test_schema.py
Fixes #673 by ensuring that collection.crs and collection.crs_wkt get an environment when needed.
=> Env wrapper refactor and correction

README.rst
Consistent python compatibility in the Readme.
=> python compatibility consistency in readme

fiona/collection.py, tests/test_schema.py
New branch based on maint-1.8 from https://github.com/Toblerity/Fiona/pull/694
=> diff fix_shp_time

appveyor.yml
This PR adds a build using Python 3.7 to Appveyor. I've also cleaned the config up a bit.
=> WIP: Added Python 3.7 to Appveyor

CHANGES.txt, fiona/__init__.py, fiona/_env.pyx, fiona/_err.pxd, fiona/_err.pyx, fiona/env.py, fiona/gdal.pxi, setup.py, tests/test_env.py
=> Patch GDAL_DATA into environ on import of fiona.env

docs/manual.rst
and advertise fio instead.
fixes https://github.com/Toblerity/Fiona/issues/621
=> remove mention of dumpgj from manual

requirements.txt
See https://github.com/Toblerity/Fiona/pull/775
=> limit argparse <= python 3.4

fiona/ogrext.pyx, tests/test_transactions.py
=> fix typo "comitting" -> "committing"

fiona/_transform.pyx, tests/test_transform.py
=> return None and raise warning when transform_geom dst_ogr_geom is NULL

CHANGES.txt, fiona/__init__.py, setup.py
=> Specify Python versions for some requirements

setup.py
See discussion in https://github.com/Toblerity/Fiona/pull/843
=> Fix setup.py python version specifiers

README.rst
Adding an example for how to get fiona installed via pip.
=> cmd line example for Windows pip install

.travis.yml, setup.py
Fix for https://github.com/Toblerity/Fiona/issues/872:
- Fix indent of log.info("GDAL version major=%r minor=%r", gdal_major_version, gdal_minor_version)
- Add setup.py clean to travis
=> Fix setup clean

fiona/collection.py, fiona/ogrext.pyx, tests/test_collection.py
Closes #887
Same as #888, but for maint-1.9.
Was tinkering and found this worked. Figured it would be useful to add to the discussion.
=> ENH: Add include_fields option for Collection

fiona/_crs.pyx, tests/test_crs.py
=> Add option in crs_to_wkt to check if input objects have the to_wkt method

fiona/__init__.py, tests/test_open.py
=> BUG: Ensure crs_wkt passed in when writing memfile

docs/manual.rst, fiona/collection.py, tests/test_collection.py
Improve documentation for the inaccuracy of spatial filtering.
Add test that fails with wheel. 
(See https://github.com/Toblerity/Fiona/issues/905)
=> Improve mask documentation

fiona/_transform.pyx, tests/test_transform.py
Fix axis ordering of fiona.transform (see https://github.com/Toblerity/Fiona/issues/919)
=> Fix axis ordering for fiona.transform

fiona/io.py, tests/test_memoryfile.py
=> Allow zipmemoryfile layer inference

CHANGES.txt, appveyor.yml, fiona/__init__.py, fiona/ogrext.pyx, tests/test_memoryfile.py
Prevents the crash reported in #937. Look reasonable to you @rbuffat ?
=> Raise OSError when VSIFOpenL fails

CHANGES.txt, fiona/__init__.py, fiona/fio/cat.py, tests/test_fio_cat.py
=> No longer cut by default

fiona/ogrext.pyx, tests/test_collection.py
Ref: https://github.com/geopandas/geopandas/issues/1611
=> BUG: Allow property name as empty string

README.rst, docs/conf.py, docs/manual.rst, fiona/__init__.py, fiona/_crs.pyx, fiona/_env.pyx, fiona/_err.pyx, fiona/fio/bounds.py, fiona/fio/calc.py, fiona/fio/cat.py, fiona/fio/collect.py, fiona/fio/distrib.py, fiona/fio/filter.py, fiona/fio/helpers.py, fiona/ogrext.pyx, tests/test_binary_field.py, tests/test_collection.py, tests/test_crs.py, tests/test_encoding.py, tests/test_feature.py, tests/test_fio_bounds.py, tests/test_unicode.py
This PR cleans-up and removes various Python 2 Unicode conventions.
=> Remove Python 2 Unicode conventions

fiona/drvsupport.py, tests/test_open.py
See https://github.com/Toblerity/Fiona/pull/999
=> Enable SQLite driver

setup.py
Saw this warning: `Unknown distribution option: 'requires_python'`
=> BUG: requires_python->python_requires in setup

.github/workflows/ci_linux.yml
=> Add GDAL 3.4.0 to linux CI build matrix

CHANGES.txt, fiona/collection.py, tests/test_bytescollection.py
=> Remove hard-coded BytesCollection encoding

CHANGES.txt, fiona/ogrext.pyx
=> Clean up files left by MemoryFileBase

CHANGES.txt, fiona/drvsupport.py, tests/test_drvsupport.py
Also reformat.
Towards resolving #935 #1031
=> Make tests less specific about feature equality

CHANGES.txt, fiona/env.py, fiona/path.py, fiona/session.py, requirements-dev.txt, requirements.txt, setup.py, tests/test_env.py, tests/test_http_session.py
Intent here is to support AWS credential refresh and get fiona 1.9 on the same page as rasterio 1.3.
Resolves gh-1055
=> Update Env and Session classes, from rasterio's master

fiona/collection.py, fiona/drvsupport.py, fiona/fio/load.py, tests/test_collection.py, tests/test_fio_load.py
Is this something you would be interested in? If so, I can add some tests, etc. Target version 1.9.
=> ENH: Auto-detect driver in writing mode

CHANGES.txt, docs/cli.rst, fiona/collection.py, fiona/errors.py, fiona/fio/cat.py, fiona/ogrext.pyx, tests/test_collection.py, tests/test_fio_cat.py
This is a backport of #961 from the master branch to the maint-1.9 branch.
=> ENH: Add 'where' SQL clause to set attribute filter

tests/conftest.py, tests/test_bounds.py
=> Use fiona meta in tests

CHANGES.txt, fiona/__init__.py, fiona/collection.py
=> Extend Collection with an exit stack

fiona/__init__.py, fiona/_env.pxd, fiona/_env.pyx, fiona/crs.pyx
=> CLN: Remove unused osr_from_crs & update crs_wkt docstrings

CHANGES.txt, fiona/fio/bounds.py, fiona/fio/calc.py, fiona/fio/cat.py, fiona/fio/collect.py, fiona/fio/distrib.py, fiona/fio/dump.py, fiona/fio/filter.py, fiona/fio/info.py, fiona/fio/insp.py, fiona/fio/load.py, tests/test_fio_calc.py
=> Avoid unintentionally catching BrokenPipeError

CHANGES.txt, fiona/model.py, tests/test_model.py
=> Add __geo_interface__ to Feature

CHANGES.txt, fiona/model.py
=> Prevent empty geometries arrays from surfacing in non-collections

docs/manual.rst
This is the value in fiona 1.9
=> Update docs with value of fiona.FIELD_TYPES_MAP

CHANGES.txt, fiona/ogrext.pyx, tests/test_geojson.py, tests/test_schema.py
=> Check that string_list is not null

README.rst
- Add --no-binary install option to Readme
- Remove Fiona 1.9 (coming soon)
=> Add --no-binary install option to Readme

CHANGES.txt, fiona/fio/load.py, tests/test_fio_load.py
=> Append mode for fio-load

README.rst
Same changes as in https://github.com/Toblerity/Fiona/pull/1233 and https://github.com/Toblerity/Fiona/pull/1232, but adapted for master.
=> Update Readme for master

fiona/__init__.py, fiona/session.py
=> fix documentation formatting

docs/manual.rst
Most of the work is switching over to using coutwildrnp.zip in the examples.
Resolves #1245
=> Modernize the manual

CHANGES.txt, fiona/collection.py
=> Accept rasterio CRS objects

CHANGES.txt
It was lost at some point in time.
=> Bring back 1.8.22 info to the changelog

CHANGES.txt, fiona/_vendor/munch/LICENSE.txt, fiona/_vendor/munch/__init__.py, fiona/_vendor/munch/python3_compat.py, fiona/fio/helpers.py, pyproject.toml
=> Vendor munch and hard code its version

docs/fiona.rst, fiona/__init__.py
=> Fix and format docs for functions in __init__.py

fiona/_geometry.pyx
Since this change #1163, this started showing up in the logs recently for a CSV file without a geometry:
```python
>>> fds = fiona.open("file.csv")
>>> next(iter(fds))
ERROR 10: Pointer 'hGeom' is NULL in 'OGR_G_GetGeometryType'.
```
Note: `OGR_G_GetGeometryType` returns 0 if NULL, so it works as is. Just adds a lot of error messages that can make you think there is an issue when there isn't one.
=> BUG: Handle getting geometry type with NULL geometries

fiona/_geometry.pyx, fiona/model.py
Most of the enhancements are the result of removing extra dictionary copies/creations.
1. Improve dictionary handling in `.from_dict()` methods. If passing kwargs to method, the new methods are faster.
2. Remove dictionary unpackings where they are unnecessary.
3. Create a _GEO_TYPES dictionary to avoid the creation of a list in decode()
=> Some performance enhancements to model.py

.readthedocs.yaml, readthedocs.yml
Based on [this template](https://docs.readthedocs.io/en/stable/config-file/v2.html#conda) for the version 2 configuration.
=> Update to version 2 ReadTheDocs configuration file

tests/test_memoryfile.py
This was missed with #1193 , sorry for the misfire on my previous PR
=> test: sort listdir before comp

.github/workflows/tests.yaml, .github/workflows/tests.yml, CHANGES.txt, environment.yml, fiona/model.py, fiona/session.py, pyproject.toml, pytest.ini, requirements-dev.txt, tests/conftest.py, tests/test_model.py
=> Preserve the null properties and geometry of a Feature

CHANGES.txt, fiona/ogrext.pyx
=> Resolves #1278

.readthedocs.yaml, CHANGES.txt, environment.yml
=> Backport RTD fixes from the master branch

CHANGES.txt, Dockerfile, Makefile, fiona/_geometry.pyx, fiona/gdal.pxi, tests/conftest.py, tests/data/multicurve.gml, tests/data/multicurve.xsd, tests/test_curve_geometries.py
As we already do for geometry instances.
Resolves #1311.
=> Translate schema geometry type to a linear type

.github/workflows/test_gdal_latest.yml, .github/workflows/tests.yml, CHANGES.txt, README.rst, tests/test_collection.py
=> Update "master" to "main"

.github/workflows/tests.yml, tests/test_bounds.py, tests/test_memoryfile.py, tests/test_slice.py
As in https://github.com/rasterio/rasterio/pull/3084.
=> Specifically run tests on macos-13 and macos-14

CHANGES.txt, Makefile, fiona/_vsiopener.pyx, fiona/gdal.pxi, fiona/ogrext.pyx
This resolves the only remaining gcc 13 compiler warning.
See #1365
=> Use CSLConstList ctypedef where appropriate

Makefile, fiona/__init__.py
And add them to the definition of `open()`!
Resolves #1280
=> Add documentation about ignore_fields and friends

CHANGES.txt, Makefile, fiona/__init__.py, tests/test_pyopener.py
Release is here https://github.com/Toblerity/Fiona/releases/tag/1.10b2.
=> Rel 1.10b2

CHANGES.txt, fiona/__init__.py
=> Rel 1.10b3

.github/workflows/test_gdal_latest.yml
Fixes the path on which the CI is run.
=> test_gdal_latest.yml: Actually run on PRs touching this file

docs/install.rst
Update text about Python requirements. Fiona 1.9 is no longer "coming soon."
=> docs: update text about python requirements

CHANGES.txt, Makefile, fiona/crs.pyx, tests/test_crs.py
=> Avoid printing representations of NULL objects

CHANGES.txt, appveyor.yml, docs/cli.rst, docs/conf.py, fiona/__init__.py, fiona/_path.py, fiona/_vsiopener.pyx, fiona/drvsupport.py, fiona/env.py, fiona/fio/collect.py, fiona/fio/dump.py, fiona/inspector.py, fiona/logutils.py, fiona/meta.py, fiona/session.py, fiona/vfs.py, tests/test_bigint.py, tests/test_datetime.py
=> Rel 1.10.1

CHANGES.txt, fiona/errors.py, fiona/ogrext.pyx
To help with the situation in #1451.
=> Improve the exception raised by JSONField.get()

FAQ.rst
To try to explain why the project publishes few wheels and few drivers.
=> Add frequently asked questions about wheels
