- fiona/_drivers.pyx
- setup.py
The _drivers.pyx module has also been modernized. It's now the same as Rasterio's.
In setup, package that data when envvar PACKAGE_DATA=1. GDAL_CONFIG and PROJ_LIB envvars can be used to point to the sources.
Also switch over to setuptools.extension as in Rasterio.
> Connect code to GDAL and PROJ data within wheels.

- fiona/fio/bounds.py
- fiona/fio/cat.py
- fiona/fio/cli.py
- fiona/fio/fio.py
- requirements.txt
- setup.py
- tests/test_fio_bounds.py
- tests/test_fio_load.py
So we get a CLI more consistent with Rasterio, especially with regards to GeoJSON feature sequences.
Closes #174.
(Oops, misnamed this branch. I intended it to be 'issue174'.)
> Use opts from cligj

- fiona/__init__.py
To build an executable from a Python script using cx_Freeze, you do something like this:
```
pip3 install cx_Freeze
cxfreeze test.py
dist/./test
```
If we try to do this for a simple script that imports fiona, it raises an error as not all of the modules used are detected automatically. This can be worked around by manually telling cx_Freeze which modules to import. http://cx-freeze.readthedocs.org/en/latest/faq.html#problems-with-running-frozen-programs
This happens because some of the modules are only called from the Cython extensions, which cx_Freeze can't parse. We could make this easier for the user by making sure all of the modules used are imported from Python space. This shouldn't add any overhead, as the modules are already imported elsewhere.
This should help similar tools, such …
> Import all modules from Python space to help cx_Freeze et al.

- fiona/_drivers.pyx
Adds an entry for the builtin [OpenFileGDB driver](http://www.gdal.org/drv_openfilegdb.html), which is available as of GDAL 1.11.  Now you are no longer required to install the separate ArcGIS SDK required for the [FileGDB driver](http://www.gdal.org/drv_filegdb.html), at least to read file geodatabases.
I tested manually with an ArcGIS 10.0 file geodatabase, and it worked perfectly once this change was made.  I tested manually when built against GDAL 1.10, and it did not appear to cause negative side effects by referencing a driver not yet in that version; it simply didn't open with the geodatabase (as expected).
I did not test with the ArcGIS FileGDB SDK installed and enabled in GDAL, so this change may interfere with users that were expecting to get that driver by default rather than …
> Added builtin OpenFileGDB driver support

- fiona/fio/main.py
- setup.py
For #224.
Following the [rasterio model](https://github.com/mapbox/rasterio/pull/346):
1. Added `fiona.fio.main` to load entry points on import.
2. Changed the `entry_points` arg in `setup.py` to reference `fio.fio.main:cli`.
3. Added a `fiona.fio_commands` to the same place and listed subcommands.
4. Forked [`rio-plugin-example`](https://github.com/sgillies/rio-plugin-example) to create a [`fio-plugin-example`](https://github.com/geowurster/fio-plugin-example) for testing purposes.  It's not in PyPi, and I'm happy to hand it off to the Toblerity org if requested, so `pip install git+https://github.com/geowurster/fio-plugin-example` to test.
I also found that attempting to load a malformed plugin totally hoses the CLI to the point where the user has to parse the traceback to identify the …
> Enable CLI plugins

- fiona/fio/cli.py
- fiona/fio/main.py
@sgillies - as described in mapbox/rasterio@225179d30db07205108364c424d4094d61ebc4d3
I also overrode `click.Command.invoke()` in [`fiona.fio.cli.BrokenCommand()`](https://github.com/geowurster/Fiona/blob/184c074681b464dea35624fd640ea7d802e63737/fiona/fio/cli.py#L32) so that if the user attempts to execute the command they still get the help message.  Without this executing the command does nothing.  I'm [pretty sure](https://github.com/mitsuhiko/click/blob/0d9731e97c9af9e5b0f5fd8421aeb0184ad42b70/click/core.py#L712) I got the printing and exiting correct.
```console
(venv)Captain:Fiona wursterk$ fio
Usage: fio [OPTIONS] COMMAND [ARGS]...
Fiona command line interface.
Options:
-v, --verbose  Increase verbosity.
-q, --quiet    Decrease verbosity.
--version      Print Fiona version.
--help …
```
> Better broken plugin handling

- fiona/inspector.py
The original nested with statement in inspector.py was syntax that was not introduced until Python 2.7.  This alternative, equivalent version is specified in PEP343.
Without these changes, this module will fail with syntax error on Python 2.6
> Restore Python 2.6 support

- fiona/fio/bounds.py
- fiona/fio/cat.py
- fiona/fio/info.py
Click handles this automatically - `raise click.Abort()` instead.  Closes #234.
> Remove sys.exit() calls from CLI

- fiona/fio/cat.py
- fiona/fio/options.py
- tests/fixtures.py
- tests/test_fio_cat.py
- tests/test_fio_load.py
Closes #241
Closes #240
@sgillies can you make sure I'm on the right track with my change to the [`fio load --sequence`](https://github.com/geowurster/Fiona/commit/1846951e97887f74e5e6312a05593d26b47bd876#diff-052c7c2327e7f08f4b54f8cc8f075331R499) help string?  It was using [cligj](https://github.com/mapbox/cligj/blob/master/cligj/__init__.py#L83-L88) but that help string only covers writing GeoJSON rather than reading.
I should have split this into 3 or 4 separate commits and 1 PR but its too late now (unless some of these changes need to be removed in which case I'll make the modifications)!
> Normalize --opt_opt, let fio-load --dst-crs default to --src-crs, and clarified some docstrings.

- fiona/ogrext.pyx
- tests/test_props.py
Closes #245.
Now (after we merge this) when you open a GeoJSON file which has features with object (not just number or string) properties using the OGR GeoJSON driver (ie with `fiona.open()`) those properties will return to you as Python objects (not JSON-encoded strings).
NB that there is no "dict" type in OGR, so when serializing, you must set the type in the schema to "str". See the example in the new tests.
> Properly handle JSON when reading OGR string fields

- docs/cli.rst
- fiona/fio/filter.py
- requirements.txt
- setup.py
- tests/test_fio_filter.py
I started writing this as a standalone script and realized it might be useful as a built in `fio` command.
The `fio filter` command reads GeoJSON features from stdin and writes the feature to 
stdout *if* the provided expression evalutates to `True` for that feature.
For example to create a geojson feature collection containing large polygons only:
fio cat data.shp \
| fio filter "f['properties']['area'] > 1000.0" \
| fio collect > large_polygons.geojson
With the munch library, we can use dot notation for convenience 
fio cat data.shp \
| fio filter "f.properties.area > 1000.0" \
| fio collect > large_polygons.geojson
The python expression is evaluated in a restricted namespace, what is allowed in that namespace is TBD. For now it's just (`sum`, `min`, `max`), the shapely `shape` …
> CLI for filtering features, fio filter

- fiona/__init__.py
- fiona/ograpi1.pxd
- fiona/ograpi2.pxd
- fiona/ogrext1.pyx
- fiona/ogrext2.pyx
- tests/test_remove.py
As suggested in #285.
This was slightly more tricky than I initially realised, as OGR needs to know which driver to use in order to delete the data source.
I've only implemented this for GDAL 1.x for now, and still need to write the function documentation. Posting here for comment.
> Initial attempt at fiona.remove for deleting data sources

- fiona/fio/cat.py
- tests/test_fio_cat.py
This is working but needs some review. 
It should work with `--record-buffered` and `--no-record-buffered`, and with line-delimited and rs-delimited sequences. 
if we're not parsing the json, we can't transform it so the `--src-crs` option isn't compatible with `--no-parse` and raises a click usage error.
I'm not thrilled at adding lots of if statements everywhere; there might be an entirely different way to structure this logic that doesn't result in so many nested conditionals.
resolves #306
> add a --no-parse option to fio collect

- setup.py
Also made the .format() Python 2.6 compliant.
This is the same PR as #298.  My git-fu was not good enough to figure out git "squashing".
> Changed gdal_output[3] to gdalversion in copy_gdalapi()

- fiona/fio/ls.py
- setup.py
- tests/test_fio_ls.py
Related to https://github.com/Toblerity/Fiona/issues/316
@sgillies While looking at #316 it seems useful to have a CLI command for listing the layers contained within a datasource.
```console
$ mkdir datasource
$ ogr2ogr datasource/layer1.shp tests/data/coutwildrnp.shp
$ ogr2ogr datasource/layer2.shp tests/data/coutwildrnp.shp
$ fio ls datasource/ --indent 4
[
"layer1",
"layer2"
]
```
```console
$ fio ls --help
Usage: fio ls [OPTIONS] INPUT
List layers in a datasource.
Options:
--indent INTEGER  Indentation level for JSON output
--help            Show this message and exit.
```
> New CLI command for listing layers: fio ls

- .travis.yml
- fiona/fio/cat.py
- fiona/fio/info.py
- fiona/fio/options.py
- tests/test_cli.py
- tests/test_fio_info.py
- tests/test_fio_load.py
Closes #299 
Closes #316 
@sgillies Ready for review.
This PR adds `--layer` to `$ fio info` to let users specify which layer they want to run a report on, and `--layer` to `$ fio load` so users can specify which layer they want to load data into.
**info example**
```console
$ fio info --layer routes tests/data/test_gpx.gpx --name
/Users/wursterk/code/Fiona/fiona/fio/info.py:83: RuntimeWarning: Layer does not support counting Setting 'count' to 'null'
warnings.warn(msg, RuntimeWarning)
routes
```
**load example**
```console
$ fio cat tests/data/coutwildrnp.shp \
| fio load OUT.gdb -f FileGDB --src-crs EPSG:4326 --sequence --layer new
$ fio ls OUT.gdb
["new"]
```
This also addresses an issue where `$ fio info` crashed when `len(collection)` crashed so now we catch the exception, issue a …
> Add --layer to $ fio info and $ fio load

- fiona/__init__.py
- fiona/ogrext.pyx
- setup.py
This PR includes two updates:
- The user is presented a warning if he uses fiona 1.x with gdal2 when he imports fiona
- The FIELD_TYPES list is extended with the 64bit Integer Types of gdal2.0.  64bit integers are thus internally treated as normal integers. 
This should have no effect when gdal1.x is used. For some drivers (e.g. shapefile), integer fields with a large enough length are treated as 64bit integer in gdal2.x while as "normal" 32bit integers in gdal1.x. Adding the 64bit Integer type to the FIELD_TYPES should thus fix the 'IndexError: list index out of range' present in some bug reports of the past.
> Warn users if they use gdal2 with fiona 1.x

- fiona/ogrext2.pyx
As title. `malloc` was missing a corresponding `free`.
> Free memory malloc'ed in string_list. Fixes #337.

- fiona/fio/cat.py
- fiona/fio/dump.py
- fiona/fio/options.py
- tests/test_fio_cat.py
- tests/test_fio_dump.py
For #349, adds `--layer` to `cat` and `dump`.  `fio cat` layer indexing is by name only to keep things simple.
The layer test function in `test_fio_cat.py` isn't very comprehensive but I didn't want to add a new test data source and couldn't seem to get any features out of `test_gpx.gpx`.  I did a better feature count test against a temp .gdb created with:
```
$ fio cat coutwildrnp.shp \
| fio filter "f.properties.NAME[:5] == 'Mount'" \
| fio collect \
| fio load multilayer.gdb --driver FileGDB --layer mountains
$ fio cat coutwildrnp.shp \
| fio filter "f.properties.NAME[:5] != 'Mount'" \
| fio collect \
| fio load multilayer.gdb --driver FileGDB --layer others
$ fio cat multilayer.gdb --layer "1.mountains,1.others" | wc -l 
67
```
> Multilayer

- CHANGES.txt
- fiona/__init__.py
- setup.py
Debian builds were broken by this regression.
> Don't copy files for clean target

- fiona/fio/env.py
- fiona/fio/main.py
This command line option gives the GDAL Version that Fiona is using when running `fio` commands.
Console example on Linux:
```
$ fio env --gdalversion
GDAL Version is 1.11.2
```
There could possibly be a use case if have multiple installations of GDAL on a system.  I was using this on Travis to figure out if the correct GDAL version was being used by Fiona.  I'm not sure if this is really useful.
> Add --gdal-version command line option to fio

- .travis.yml
- scripts/travis_gdal_install.sh
This PR builds only one version of GDAL per Travis job and prunes all Python versions but 2.7 and 3.5. Fiona doesn't use any 3-only features and so 3.5 is as good as any other Python 3.x version. Benefits: faster builds when we have no caches, such as when we want to update GDAL versions, and smaller caches.
> Single gdal version jobs

- fiona/ogrext1.pyx
- fiona/ogrext2.pyx
In case the date in the input isn't correct (yielding any of y=0, and/or m=0, and/or d=0), there is an error in datetime.date(). Protect against such case by defaulting to unix timestamp 0 (Jan 1st, 1970)
> Protect against bad dates

- CHANGES.txt
- fiona/__init__.py
- fiona/collection.py
- tests/test_bigint.py
- tests/test_multiconxn.py
- tests/test_props.py
- tests/test_schema.py
- tests/test_unicode.py
From `CHANGES.txt`:
```
Future Deprecation:
- `Collection.__next__()` is buggy in that it can lead to duplication of 
features when used in combination with `Collection.filter()` or
`Collection.__iter__()`. It will be removed in Fiona 2.0. Please check for
usage of this deprecated feature by running your tests or programs with
`PYTHONWARNINGS="always:::fiona"` or `-W"always:::fiona"` and switch from
`next(collection)` to `next(iter(collection))` (#301).
```
Resolves #301
> Deprecate Collection.__next__()

- .travis.yml
I also tried updating Appveyor to `3.5.2`, but the build failed so I reverted and left it at `3.4`: https://ci.appveyor.com/project/sgillies/fiona/build/1.0.177
> Python 3.6 testing

- fiona/collection.py
- fiona/ogrext1.pyx
- fiona/ogrext2.pyx
- tests/conftest.py
- tests/test_bytescollection.py
- tests/test_collection.py
- tests/test_drivers.py
- tests/test_fio_cat.py
- tests/test_fio_collect.py
- tests/test_fio_dump.py
- tests/test_fio_info.py
- tests/test_fio_load.py
- tests/test_fio_ls.py
- tests/test_layer.py
- tests/test_listing.py
- tests/test_unicode.py
- tests/test_vfs.py
This is a PR for https://github.com/Toblerity/Fiona/issues/414
Especially two of the commits should be reviewed:
In 90846683f8cfe35103a193e31367d990f10a43ab, / is used a path separator for /vsimem/ paths. Unfortunately my editor removed some whitespace, only line `vsi_filename = os.path.join('/vsimem', uuid.uuid4().hex)` changed to `vsi_filename = '/vsimem/{}'.format(uuid.uuid4().hex)`. 
In 9c1b59ac2b83d77a9cc2120164acff8d9059d709, the encoding of a bytescollection is fixed to utf8 instead of  the encoding of the current session. 
There are still FIXME Windows in test_multiconxn.py. 
Currently a lot of tests use the same "hardcoded" path. This could be refactored in a future step.
> Fix windows tests

- tests/test_fio_ls.py
Since this reads layer names from multiple files, there's no guarantee that they will be in order since the filesystem can iterate in any order.
I hope I've diagnosed this correctly, but I've hit this same failure in more than one build on multiple systems ([Fedora 25](https://copr-be.cloud.fedoraproject.org/results/qulogic/geopy/fedora-25-x86_64/00521997-python-fiona/build.log.gz), [Fedora 26](https://copr-be.cloud.fedoraproject.org/results/qulogic/geopy/fedora-26-x86_64/00521997-python-fiona/build.log.gz), [Fedora Rawhide](https://copr-be.cloud.fedoraproject.org/results/qulogic/geopy/fedora-rawhide-x86_64/00521997-python-fiona/build.log.gz)) which went away after this patch ([builds](https://copr.fedorainfracloud.org/coprs/qulogic/geopy/build/522001/)).
> TST: Fix flaky ls test.

- docs/manual.rst
Geopackages start indexing at 1, as this is the default auto-increment id behaviour. Asking for a `geopackage_file[0]` will return `None`. Apparently, GDAL indices have [no guarantee of start values of contiguity](https://trac.osgeo.org/gdal/ticket/356). This makes for interesting errors in retrieving indices from spatial indexes, for example. It can also produce incorrect values with negative indexing.
This PR adds this information to the manual.
In my specific case, I decided to construct a [mapping dictionary from indices I get from ``enumerate()`` to what GDAL expects](https://github.com/cmutel/pandarus/commit/0b0915b1f7ff2dc7344639986ba4294187cf313b#diff-b5068aab3983338209fe38d1ae80bb02), but this is obviously not a general solution for Fiona.
> Add note about some possible unexpected indexing behaviour

- fiona/_err.pyx
fix for Fiona exceptions generated from GDAL's Error handling, from #455 
This doesn't entirely resolve #455 because `fio info` will raise and exception an terminate because of a GDALError that is a CE_Warning (err_type = 2).  This merely provides better information for the cause of the Error (or Warning).
> Fix for GDAL Error handling

- .travis.yml
- scripts/travis_gdal_install.sh
Also dropped build of 1.9.2 (released 2012). Oldest build is now 1.11.2 (released 2015).
There are a few failures against trunk we should look into.
Closes #479.
> Build gdal-trunk on travis (allow failure)

- .gitignore
- fiona/_shim1.pxd
- fiona/_shim1.pyx
- fiona/_shim2.pxd
- fiona/_shim2.pyx
- fiona/_shim22.pxd
- fiona/_shim22.pyx
- fiona/errors.py
- fiona/ogrext.pyx
- fiona/ogrext2.pxd
- scripts/travis_gdal_install.sh
- tests/conftest.py
- tests/test_geopackage.py
- tests/test_transactions.py
This PR implements transactions when using `collection.writerecords` in GDAL 2.x, as discussed in #476. Currently it's hard-coded to use a transaction size of 20,000 (the same as `ogr2ogr`). This significantly speeds up writing GPKG files.
I'm not sure of the best way to expose the transaction size to the user. Is it a property of the collection, or an argument to the `writerecords` call?
This should have no impact on drivers which don't support transactions.
> Initial implementation of transactions in writerecords

- tests/conftest.py
- tests/test_collection.py
- tests/test_collection_crs.py
- tests/test_profile.py
This PR fixes the WKT CRS errors we're getting with GDAL trunk, e.g.:
https://travis-ci.org/Toblerity/Fiona/jobs/297667083
It looks like GDAL is converting the CRS from ESRI WKT to OGC WKT. Older versions don't do this so we need to handle both in the tests.
https://gis.stackexchange.com/a/70286/12420
> GDAL 2.3.x silently converts ESRI WKT to OGC WKT.

- tests/test_multiconxn.py
The dataset wasn't being closed properly and a race condition in
garbage collection was causing the files to be deleted before
they were closed.
> Fixed some tests that were being skipped on Windows.

- README.rst
Add a badge to the README to show Windows build status on the front page.
> Add Appveyor badge to README

- fiona/fio/load.py
As discussed in #499, this adds an option to declare the output enconding of `fio load`. This is untested unfortunately because the documented setup did not lead to a working development environment for me.
A minimal test file with characters not covered in latin1 can be found [here](https://gist.github.com/heyarne/f6d7f07080422fde285bf1bb30fefff4).
> Add encoding option to fio load

- appveyor.yml
- fiona/vfs.py
This PR fixes a regression introduced in the handling of paths beginning with a drive letter on Windows. Previously a path like `"C:\hello\world.shp"` would be interpreted as a URL with scheme `"C"` and a path `"/hello/world"`, which is incorrect. This type of path is now detected on Windows and handled correctly. True VFS paths should still work as expected.
Closes #505.
> Fix handling of paths on Windows. Closes #505.

- setup.py
This PR builds the `_transform` module using the C++11 standard.
I've not tested this on Windows. I suspect it will break, as MSVC uses a different flag? `/std:c++11`?
Also, VS2008 (which must be used to build Python 2.7 modules) does not support C++11. If I understand this correctly, this means a Python 2.7 + GDAL 2.3 build will be impossible. If we include this, it will also mean the .cpp source distribution wont work for Python 2.x. https://stackoverflow.com/questions/20302891/visual-studio-2008-with-c11
> [WIP] Use C++11. Closes #514.

- tests/conftest.py
This PR corrects a mistake in #495. The regex wasn't actually matching the new CRS in GDAL 2.3 - there are other issues still causing tests to fail in trunk, so it's difficult to spot.
> Fixed WGS 84 CRS regular expression.

- fiona/_shim1.pxd
- fiona/_shim1.pyx
- fiona/_shim2.pxd
- fiona/_shim2.pyx
- fiona/_shim22.pxd
- fiona/_shim22.pyx
- fiona/ogrext.pyx
- fiona/ogrext2.pxd
- tests/test_subtypes.py
This PR adds support for the "bool" field subtype when using GDAL 2.x. When using GDAL 1.x the subtype is simply ignored - you can still pass "bool" in the schema but an "int" will be written.
Closes #524.
> Added support for bool field subtype in GDAL 2.x

- fiona/collection.py
- fiona/ogrext.pyx
- fiona/ogrext1.pxd
- fiona/ogrext2.pxd
- tests/test_collection.py
This PR is my first attempt at ignoring fields using the OGR API, as discussed in #429.
Is there a better way to create a `NULL` terminated `char **` array?
The feature is exposed as a keyword argument on `fiona.open`, e.g.
```
collection = fiona.open(WILDSHP, "r", ignore_fields=["AREA", "STATE"])
```
I don't think it would be to difficult to implement a `usecols` option for whitelisting, as the OGR layer is already open by the time the API method is called.
The fields are not *hidden* from the user, but their values are not returned. Instead the fields are populated with `None`. This isn't something I've decided - it's just what it's doing.
I haven't done any benchmarking on this to see if it actually makes a difference for large datasets.
> First attempt at ignoring fields

- .travis.yml
- scripts/travis_gdal_install.sh
SVN checkout of gdal trunk on travis fails with:
> Authentication realm: <https://svn.osgeo.org:443> OSGeo Login
Password for 'travis': 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
This is possibly related to https://trac.osgeo.org/osgeo/ticket/2128
Fix: Change to gdal's github mirror.
Additionally, bump gdal to 2.1.4 and 2.2.3
> Fix trunk repo

- fiona/_geometry.pxd
- fiona/_geometry.pyx
- fiona/collection.py
- fiona/errors.py
- fiona/ogrext.pyx
- tests/test_schema_geom.py
This PR modifies the validation done when writing geometries to ensure they match the collection schema.
The existing behaviour of specifying a single geometry type is unchanged:
```
fiona.open(..., schema={"geometry": "Point", ...})
```
Alternatively you can specify a list of types:
```
fiona.open(..., schema={"geometry": ("Point", "LineString", "Polygon", ...})
```
Or allow any type:
```
fiona.open(..., schema={"geometry": "Unknown", ...})
```
This works for the edge cases I could think of (e.g. ESRI Shapefile doesn't care between LineString/MultiLineString, Polygon/MultiPolygon), but I may have missed something out.
A new exception is raises if a geometry is written that doesn't match the schema: `GeometryTypeValidationError`.
It's possible to specify a schema that isn't actually valid …
> Geometry type schema is now more flexible

- fiona/_shim1.pxd
- fiona/_shim1.pyx
- fiona/_shim2.pxd
- fiona/_shim2.pyx
- fiona/_shim22.pxd
- fiona/_shim22.pyx
- fiona/ogrext.pyx
- fiona/ogrext2.pxd
- tests/test_feature.py
This PR uses `OGR_F_SetFieldNull` which was introduced in GDAL 2.2. Without it the `test_feature_null_field` test fails for the GeoJSON driver.
> Added set_field_null for GDAL 2.2+

- fiona/ogrext.pyx
- tests/conftest.py
- tests/test_binary_field.py
- tests/test_geopackage.py
- tests/test_subtypes.py
- tests/test_unicode.py
Another batch of commits extracted from #532.
https://github.com/Toblerity/Fiona/commit/6ebf990d7de43636a98796debb7aa932693ef546 fixes an issue whereby the binary field test ways always skipped when running on CI.
> Some fixes for Python 2.7, and a fix for the binary field test

- docs/cli.rst
- docs/fiona.fio.rst
- fiona/__init__.py
- fiona/errors.py
- fiona/fio/rm.py
- fiona/ogrext.pyx
- fiona/ogrext2.pxd
- setup.py
- tests/test_fio_rm.py
- tests/test_remove.py
This PR adds the `rm` command to `fio`, which can be used to delete a datasource or a specific layer in a multi-layer datasource.
```
$ fio rm countries.shp
$ fio rm --layer forests land_cover.gpkg
```
The `fiona.remove` function has been extended to support a `layer` keyword argument.
Closes #401.
> Added `fio rm` command

- appveyor.yml
- Pythons: 2.7 and 3.6
- GDAL: 1.11.4, 2.2.3, and trunk (from GIS internals)
I'm still not using conda-forge for GDAL because of the value in testing against the GDAL trunk.
> Expand range of Python and GDAL versions in Appveyor matrix

- tests/test_binary_field.py
- tests/test_fio_calc.py
- tests/test_memoryfile.py
This fixes a few warnings raised in the tests.
There is still one left from fio.calc that I can't figure out.
```
tests/test_fio_calc.py ....                                                                                               [100%]
======================================================= warnings summary ========================================================
tests/test_fio_calc.py::test_calc_seq
/Users/snorf/miniconda3/envs/python36/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
return f(*args, **kwds)
-- Docs: http://doc.pytest.org/en/latest/warnings.html
```
> Fixed some warnings in tests

- .travis.yml
- fiona/vfs.py
- scripts/travis_gdal_install.sh
- tests/conftest.py
- tests/test_bytescollection.py
- tests/test_collection.py
- tests/test_vfs.py
This PR implements https://github.com/Toblerity/Fiona/issues/573
It includes two bigger changes and a few smaller ones:
**Disable test_grenada_bytes_geojson**
In Gdal 2.3 no FionaValueError is thrown anymore. This is possible due to [RFC70](https://trac.osgeo.org/gdal/wiki/rfc70_output_format_guess): 
> Command line utilities, when neither -f nor -of are specified (note: since r39878 both switches can be indifferently used), will loop through the registered drivers and check if one or several drivers, with output capabilities, declare to recognize the extension of the output filename. 
**Include vsi remote schemes**
Changes are limited to parse_paths() in vfs.py.  This function is rather complex, I hope I thought about every cases.  There are a few tests in test_vfs.py, but I think it …
> Gdal23 fixes

- README.rst
Updated README for --gdalversion/GDAL_VERSION to include minor version, e.g. `GDAL_VERSION=2.2`
Also added some more information for installation on Windows.
Closes #547.
> Updated README for --gdalversion/GDAL_VERSION.

- fiona/__init__.py
- fiona/ogrext.pyx
- tests/test_bigint.py
- tests/test_bytescollection.py
- tests/test_drivers.py
- tests/test_subtypes.py
- tests/test_version.py
- tests/test_vfs.py
Adds a named tuple with the runtime GDAL version number.
```python
import fiona
print(fiona.gdal_version.major)
print(fiona.gdal_version.minor)
print(fiona.gdal_version.release)
assert fiona.gdal_version.major >= 2
assert fiona.gdal_version >= (2, 2, 0)
```
Closes #575.
> Added fiona.gdal_version named tuple

- fiona/collection.py
- fiona/errors.py
- tests/test_datetime.py
#540 got me looking at the support for date/datetime/time fields. It's a little complicated, with different drivers having different levels of support and behaviours. I've added some tests to illustrate the current behaviour. I don't think anything needs to change, except that we should raise a more useful error when trying to create a time-type field in an ESRI Shapefile, which currently raises an unexpected KeyError.
> Test support for date/datetime/time fields

- docs/cli.rst
Also fixed formatting for `filter` example.
> Add docs for fio calc

- appveyor.yml
- fiona/_err.pxd
- fiona/_err.pyx
- fiona/fio/load.py
- fiona/ogrext.pyx
- fiona/schema.py
- fiona/schema.pyx
- setup.py
- tests/test_bigint.py
- tests/test_schema.py
- tests/test_transactions.py
Collection schemas still report 'int:9' or 'int:18' for now (with GDAL 2) but in creating a collection, 'int' means 'int64'.
Resolves #562
> Make way for int64, the best integer

- appveyor.yml
Added GDAL 2.4.0dev to appveyor, allowed to fail.
GDAL 2.3.0 is no longer allowed to fail.
Also removed GDAL 2.3.0 with Python 2.7 as they are incompatible (see #514).
> Added GDAL 2.4.0dev to AppVeyor

- tests/test_fio_ls.py
- tests/test_listing.py
Since this reads layer names from multiple files, there's no guarantee that they will be in order since the filesystem can iterate in any order.
> TST: Fix flaky listing test.

- fiona/ogrext.pyx
- tests/test_binary_field.py
In Python 2, when writing bytes data to a binary field, `UnicodeDecodeError` is possible if the field name is provided as a Unicode string, due to string formatting in `log.debug()`.
The fix doesn't solve problems with non-ASCII field names in Python 2, just allows to pass field name consisting of ASCII symbols as a Unicode string (which is convenient in case when the calling code uses `from __future__ import unicode_literals`).
The changes in test code are to make sure that all possible byte values are written correctly.
> Fix log statement causing UnicodeDecodeError in certain circumstances

- fiona/ogrext.pyx
With gdal 1.10.0 (Released in April 2013) the current "GDAL Version Information macro" was introduced. Older versions used a different version of the macro. The current version of Fiona does only follow the new macro definition. However, the documentation says that GDAL/OGR 1.8+ is supported. 
This PR makes calc_gdal_version_num and get_gdal_version_tuple aware of the different GDAL Version Information macro for OGR versions prior to 1.10.0. 
I'm not sure if there are users that use a recent version of Fiona in combination with such an old version of gdal/ogr.  Thus we could also just bump the minimal supported version of gdal to 1.10. 
However,  we currently do not test in the CI for backwards compability to the oldest supported version of gdal/ogr, which might be something that we …
> gdal version macro < gdal 1.10

- tests/test_bigint.py
- tests/test_binary_field.py
- tests/test_collection.py
- tests/test_encoding.py
- tests/test_feature.py
- tests/test_fio_collect.py
- tests/test_geojson.py
- tests/test_integration.py
- tests/test_layer.py
- tests/test_listing.py
- tests/test_non_counting_layer.py
- tests/test_revolvingdoor.py
- tests/test_rfc3339.py
- tests/test_schema.py
- tests/test_unicode.py
This leaves 4 files with unittest:
$ rg -l 'import unittest'
test_collection.py
test_geometry.py
test_multiconxn.py
test_bytescollection.py
Also fixes finding of test data in the tests that don't use the fixtures because they used to be `unittest` but now aren't, and can subsequently use the fixture.
> Cut down on unittest usage

- tests/test_bytescollection.py
- tests/test_collection.py
Something of a corollary to #651 but for collections. It doesn't drop `unittest` entirely, but does drop the use of its class methods.
> Replace unittest.assert* with plain assert in collection tests

- requirements-dev.txt
- setup.py
- tests/test_vfs.py
Its only use is an import that is never used for anything.
> Remove packaging from test requirements.

- fiona/ogrext.pyx
Python methods should not be called from `__dealloc__()` because this may cause object resurrection.
Using `cpdef` directive generates a C version of the method along with Python version, thus solving the problem.
This fixes PyPy compatibility (#553).
> Don't call Python methods from __dealloc__()

- fiona/_err.pyx
- fiona/ogrext.pyx
- fiona/ogrext1.pxd
- fiona/ogrext2.pxd
- tests/test_unicode.py
This PR fixes a bug triggered when creating a field with a name not supported by the layer encoding. Previously this would go unnoticed until a feature was written, at which point a `KeyError` is raised because the field is missing in the schema mapping. This change detects the issue at the time of creation and raises a `ValueError` with some useful information. I'd be willing to raise a more specific error if we can think of a name - `FieldCreationError`?
Closes #595.
> Fixed issue when using field names not supported by layer encoding

- fiona/_env.pyx
- tests/test__env.py
- tests/test_env.py
Towards resolving #673.
I've created GDAL and PROJ data finder classes to make the process more testable and to make it possible to test the correctness of our environment ensuring decorators by monkeypatching `sys.prefix` and `rasterio._env.__file__`.
A `GDAL_DATA` environment variable short-circuits the data search, as it did before.
> Refactor discovery of GDAL and PROJ data

- README.rst
The current link points to an old version of the docs (1.7.0), while the readthedocs link should be up to date.
> DOC: update link to docs in the README

- fiona/path.py
- fiona/session.py
- fiona/vfs.py
- tests/test_env.py
Adds the appropriate prefix to support Google Cloud Storage.
Requires support in GDAL (2.3 or newer).
> Add google cloud storage support

- docs/fiona.rst
`io` module was missing in the online docs
> Add io module to sphinx documentation

- fiona/_geometry.pyx
- fiona/compat.py
- fiona/ogrext.pyx
- tests/test_geometry.py
I saw the issue #685, and so I took a stab at it based on the discussion to see if I could help move things forward.
I commented out the debug print statements instead of deleting them so that you don't have to re-create them when you are debugging (and an official decision on what to do with them has not been reached as far as I know). However, that presents the danger of being re-introduced by accident when committing changes after debugging.
Using this example:
```python
from itertools import chain, repeat
import fiona
def test_to_file():
with fiona.Env(),fiona.open("../tests/data/coutwildrnp.shp") as collection:
features = chain.from_iterable(repeat(list(collection), 2000))
with fiona.open("/tmp/out.gpkg", "w", schema=collection.schema, crs=collection.crs, driver="GPKG") as dst: …
```
> remove per-feature logging to improve performance issue#685

- fiona/_geometry.pyx
error occured loading gpkg file containing polygons same file worked fine with previous versions of fiona failure points to this pyx file extending the ranges to have no gaps would stop error being raised and allow code to run. modulo would be 0 returning unknown rather than unsupported.
> Filling Range Gaps

- tests/data/example.topojson
- tests/test_topojson.py
Following #721 this PR adds a simple test of the TopoJSON driver.
The example data is from: https://github.com/topojson/topojson-specification/blob/master/README.md#11-examples
> Added a test for the topojson driver (requires GDAL >= 1.11)

- appveyor.yml
I've got the solution for "2.4.0" failures: actually download 2.4.0 instead of using a branch that moved on (toward 2.5), which was pointed out elsewhere.
Also, I've allowed python 2.7 failures to be ignored. We could revisit this if someone with more powershell knowledge comes along to show us how to tolerate pip's warnings about deprecation of python 2.7.
> Update GDAL 2.4.0 package on AppVeyor

- .travis.yml
- scripts/travis_gdal_install.sh
- scripts/travis_proj_install.sh
Gdal 2.5.0beta1 is released and Fiona fails to build against it: https://github.com/Toblerity/Fiona/issues/745
This PR includes the work I did in https://github.com/Toblerity/Fiona/pull/696 to support the installation of beta and rc versions of GDAL on travis.
However, GDAL 2.5.0beta1 fails to build because it has now a dependency on proj6, which I did not yet find an ubuntu package for.
> Add support for travis to build [beta|rc] versions of gdal and fiona rfc1

- .travis.yml
- appveyor.yml
Gdal 3.0.0 was released. This PR switches gdal 2.5.0beta1 with gdal 3.0.0.
> travis bump gdal to 3.0

- docs/manual.rst
As expected I did mess up the arcane RST syntax. This should hopefully fix it and make the note visible.
> Fix broken note in manual

- README.rst
The links were written for Markdown but the document is RST.
> Fixed hyperlinks in Windows section of README

- fiona/model.py
- tests/test_model.py
model.Object is the dict with deprecation warnings class. I'm not entirely certain that "model" is the best name for this module. Resolves #758.
> Add model module and tests

- fiona/__init__.py
- tests/test_listing.py
This brings it in line with the functionality of `fiona.open()`
Addresses Issue #768
> fiona.listlayer() now accepts Path objects

- tests/test_listing.py
This avoids the Windows build failure introduced in #769 by skipping this test.
The problem is that on Windows the `Path` will try to convert `zip://` so you end up with a path string passed to GDAL like `zip:\C:\Users\Snorfalorpagus\Desktop\Fiona\tests\data\coutwildrnp.zip` which isn't correct.
> Skip Path test for zip files on Windows

- requirements-dev.txt
- setup.cfg
Registering the markers used by pytest helps to prevent typos, as unknown markers in newer versions raise a warning.
https://docs.pytest.org/en/latest/mark.html#registering-marks
> Register pytest markers and upgrade pytest

- fiona/__init__.py
- tests/test_memoryfile.py
This fixes the bug reported in #781.
Is GPKG the best format for the tests?
The test probably needs to be improved before merge - I've not tested the same issue with write instead of read, although I can see it should work (because that is where the fix was copy+pasted from).
> Pass arguments when reading file-like dataset. Fixes #781.

- docs/manual.rst
- fiona/collection.py
Re https://github.com/Toblerity/Fiona/issues/740 I added notes about the transactions on write operations
- as a hint to the Fiona-using programmer in the docstring and
- as a note for everyone to see in the manual.
> DOC: Mention unique transaction per collection.write()

- setup.py
With the previous implementation, tools like poetry were pulling all the dependencies (e.g. enum34) even on newer Python versions
BTW, according to setup.py `argparse` is supposed to be installed for Python 2 only, while according to the requirements.txt it is supposed to be installed on < 3.4. Not sure which is the correct one. I opted for the requirements one
> setup.py: Use requirement specifiers

- fiona/_transform.pyx
- fiona/transform.py
- tests/test_transform.py
> modified transform geom to accept arrays of geoms

- fiona/_shim3.pyx
Fix crash when importing Fiona-1.8.10 + with GDAL 3.0.2 on Windows.
> Fix access violation on Windows

- .travis.yml
- scripts/travis_gdal_install.sh
Just some minor modifications to travis.yml:
- A  rename from "trunk" to "master" was missing
- libgdal-dev is not needed
- I assume the gdal version check supporting beta and rc versions went missing somewhere
The current matrix produces three builds for master, which takes quite some time to build. I would suggest using an explicit matrix as proposed in https://github.com/Toblerity/Fiona/pull/770 and only test master for one Python version.  Alternatives would be to not test master on travis and only on appveyor, or to try to cache the master gdal builds somehow.
> Some minor modifications to .travis.yml

- docs/manual.rst
I got an email from a user who wanted to use the Fiona manual example code in another project.
@kannes @munro @loicdtx @drnextgis @snorfalorpagus @cmutel @rouault @perrygeo, as contributors to the manual and its example code, any objections to re-licensing the examples using BSD 3-clause, like the module code?
> Relicense code in examples

- .travis.yml
* GDAL 3.0.2 -> [3.0.3](https://lists.osgeo.org/pipermail/gdal-dev/2020-January/051453.html)
* GDAL 2.4.3 -> [2.4.4](https://lists.osgeo.org/pipermail/gdal-dev/2020-January/051452.html)
* PROJ 6.2.1 -> [6.3.0](https://lists.osgeo.org/pipermail/proj/2020-January/009178.html)
> Upgrade Travis CI testing against latest GDAL and PROJ releases

- .travis.yml
- scripts/travis_gdal_install.sh
- scripts/travis_proj_install.sh
- tests/test__env.py
- tests/test_compound_crs.py
There are currently two issues with the tests and gdal master. 
The mock debian tmpdir is missing a path for gdal 3.1. I changed the creation of the mockdir to use gdal_version. However, I'm not sure if there was a reason that the paths were hardcoded and I did not notice.
The second issue is, that gdal now something returns for the  COMPD_CS projection. As far as I understand the test_compound_crs test, it is only important that a crs (empty or not) is returned and no crash happens. Thus I changed it to just test if a dict is returned. 
Finally, the PR disables that the gdal master installation is always deleted and not cached.
> Adapt travis tests to gdal master

- fiona/drvsupport.py
I was trying to append to a GeoPackage file but I was receiving a DriverError: unsupported mode: 'a'. I found it strange since the append operations seems to be supported by GDAL/OGR. Searching the issues page I found issues #839 and #840 and decided to figure out a way to make it work.
I decided to start by simply trying to add the append mode to the GPKG and GeoJSON lines in fiona/drvsupport.py and then I started doing some tests. It seems it is now able to append correctly to those two formats.
This is my first PR so feel free to guide me in the right direction if I'm doing something wrong.
> Added the append mode to GPKG and GeoJSON

- fiona/collection.py
- fiona/fio/info.py
- fiona/ogrext.pyx
- tests/conftest.py
- tests/test_bounds.py
Follow up to https://github.com/Toblerity/Fiona/pull/866 regarding OGR_L_GetExtent after writing of features. 
Currently, there are two issues:
1. Calculation of extents can fail
2. Correct calculation of extents after writing a record is driver dependant: https://github.com/OSGeo/gdal/issues/2269
Regarding 1:
- This PR disables the computations of bounds after records are written. They are lazy evaluated.
- When a bound cannot be calculated, a DriverError is raised. This leads to failed tests.
Regarding 2:
- We probably should detect cases when the calculation of bounds is not possible. ~Unfortunately, it seems as GDAL does not raise an error in this case. We could blacklist drivers.~
> Bounds can not always be calculated

- fiona/__init__.py
- fiona/ogrext.pyx
- tests/test_schema.py
Fix for https://github.com/Toblerity/Fiona/issues/848
The properties, as well as the geometry key are optional according to https://gist.github.com/sgillies/2217756#__geo_interface__ However, they are currently required by fiona. 
This PR follows the "easy" route, it checks if a schema or record has one of these keys and if not, adds either an empty dictionary for properties or 'geometry' = None for the geometry case.
> Fix optional keys required

- .travis.yml
- scripts/travis_gdal_install.sh
- scripts/travis_proj_install.sh
This PR backports changes in travis.yml applied to master to maint-1.8. 
As the build matrix with 8 gdal versions and 3 python version would be immense, I would suggest using a cross pattern:
* Testing all supported gdal versions with a single version of Python
* Testing the latest stable gdal release with all supported python versions.
> Sync travis of maint-1.8 with master

- .travis.yml
- appveyor.yml
- setup.py
https://github.com/Toblerity/Fiona/commit/724e355a9d54a883a4ae7160321275a70861fd0d removed coveralls from travis.
In case this was accidental, this PR adds coveralls to travis and appveyor. Although, it is disabled on appveyor for now as it  requires a token. 
Furthermore the PR includes https://github.com/Toblerity/Fiona/pull/874.
> Readd coveralls to CI

- fiona/collection.py
- fiona/errors.py
- fiona/ogrext.pyx
- tests/test_session.py
> ENH: Added support for geopackage metatata

- fiona/env.py
Fix for https://github.com/Toblerity/Fiona/issues/897
The `path = GDALDataFinder().search_wheel()` from rasterio is missing in Fiona: https://github.com/mapbox/rasterio/commit/059ad3e01c0da363c99cd1f2ca6c4e3353c1485c#diff-bcec099fb5186938da74b5bfc04c1476
> Search wheel first to find GDAL_DATA

- .travis.yml
- setup.cfg
- tests/test__env.py
- tests/test_compound_crs.py
As gdal 3.1.0rc3 is out I thought it would be good to enable it on travis. 
Furthermore, the PR backports the test fixes already applied to master and optimizes the compile time by disabling compiler optimizations (-O0). 
As currently the compile time of gdal, proj and fiona is >> the run time of the tests it decreases total run time of the travis build jobs. 
Compilation time of Fiona decreases from roughly 30 seconds to 15 seconds.
Compilation time of gdal master decreases from  20 minutes to 15 minutes.
> Add gdal 3.1.0 to travis of maint-1.8, improve compile time

- tests/test_version.py
I overlooked that it is not possible to parse gdal version number from the GDALVERSION environment variable for gdal master.  This PR fixes this.
> Fix failing show_version() test for gdal master

- fiona/ogrext.pyx
- tests/test_schema.py
Problem:
Some drivers create fields by default. Fiona is currently not aware of these fields. Additionally, some drivers modify the field names (e.g. Shapefile has a length restriction for field names). Fiona maintains a schema mapping between field names in the schema provided to Fiona, and the resulting field names. However, as the default fields are not considered, the resulting mapping is wrong (see https://github.com/Toblerity/Fiona/issues/916).
This PR fixes the schema mapping if a driver contains default fields. This is kind of a minimal solution, as the existence of default fields also influence the schema validation, which is not touched with this PR. This PR does not modify that only the fields in the schema provided to Fiona are validated.
Currently, schema validation requires …
> Fix schema mapping if driver includes default fields

- .travis.yml
- fiona/_shim1.pxd
- fiona/ogrext.pyx
- fiona/ogrext2.pxd
- fiona/ogrext3.pxd
- scripts/check_deprecated.py
In https://github.com/Toblerity/Fiona/pull/909 I noticed that some deprecated GDAL methods are only partially replaced. 
I created a small helper script to identify these methods. In this PR I already replaced the trivial cases. The current output of the script is as follows:
```
fiona/_env.pyx
151	return GDALGetDriverCount() + OGRGetDriverCount()
397	OGRRegisterAll()
457	for i in range(OGRGetDriverCount()):
458	drv = OGRGetDriver(i)
fiona/_geometry.pxd
97	int     OGR_G_GetCoordinateDimension (void *geometry)
fiona/_geometry.pyx
184	self.ndims = OGR_G_GetCoordinateDimension(geom)
fiona/ogrext.pyx
1498	if not OGR_Dr_TestCapability(cogr_driver, ODrCDeleteDataSource):
fiona/ogrext2.pxd
240	int     OGR_Dr_TestCapability (void *driver, const char *)
fiona/ogrext3.pxd
241	int …
```
> [WIP] Replace deprecated GDAL methods

- .travis.yml
- CHANGES.txt
- fiona/_shim1.pxd
- fiona/_shim1.pyx
- fiona/_shim2.pxd
- fiona/_shim2.pyx
- fiona/_shim22.pxd
- fiona/_shim22.pyx
- fiona/_shim3.pxd
- fiona/_shim3.pyx
- fiona/drvsupport.py
- fiona/ogrext.pyx
- fiona/ogrext2.pxd
- fiona/ogrext3.pxd
- scripts/travis_filegdb_install.sh
- scripts/travis_gdal_install.sh
- tests/conftest.py
- tests/test_drvsupport.py
- tests/test_transactions.py
FileGDB is included in supported_drivers, but currently not tested. 
This PR:
- Adds FileGDB support to travis using https://github.com/Esri/file-geodatabase-api
- Updates drvsupport for  FileGDB
- Fixes an issue when a driver does not support transitions (such as FileGDB), writing records results in `fiona.errors.TransactionError: Failed to commit transaction` (https://travis-ci.org/github/rbuffat/Fiona/jobs/718900437)
It seems that ints written with the FileGDB driver are read as floats back. Not sure why.
I'm not that much of a fan of using the FileGDB API, but as long as we include FileGDB in drvsupport, I prefer if we test the driver. If it causes problems, the support can be removed again.
> Include FileGDB in travis and fix related issues

- CHANGES.txt
- fiona/ogrext.pyx
- requirements-dev.txt
- tests/test_write.py
> Silence errors on overwriting GeoJSON

- fiona/__init__.py
`this_schema` and the conversion to OrderedDict is not used. Unsure though if it is needed at all, as there seemed to be no issue without it.
https://github.com/Toblerity/Fiona/blob/c2cbbab04ff7d3eaf1a11ab767d7f86e918a5edf/fiona/__init__.py#L219-L232
> this_schema not used for fp_writer

- fiona/drvsupport.py
- tests/test_datetime.py
The GPKG driver now supports unknown timezones (https://github.com/OSGeo/gdal/issues/2898) and the test_datetime.py/test_no_unknown_timezone fails because of this for gdal 3.1.3 and master. But _driver_supports_unknown_timezones() is never used except in this test. Thus it is best to remove it as it tests only gdals behavior.
> Remove _driver_supports_unknown_timezones() from drvsupport

- fiona/_loading.py
@sgillies is this what you had in mind? 
I'm still a bit concerned regarding the `import fiona._err`, especially as we do not test this case on the CI. Would a dedicated module for just this task make sense?
> Refactor _loading to avoid circular import

- fiona/_err.pxd
- fiona/_err.pyx
- fiona/_geometry.pxd
- fiona/_geometry.pyx
- fiona/_shim1.pyx
- fiona/gdal.pxi
- fiona/ogrext.pyx
- fiona/ogrext1.pxd
- fiona/ogrext2.pxd
- fiona/ogrext3.pxd
- tests/test_datetime.py
- tests/test_slice.py
Today I tried to merge maint-1.8 into maint-1.9 and stumbled on a few failing tests (new to maint-1.8) related to wrapping GDAL function in exc_wrap* functions (See PR https://github.com/Toblerity/Fiona/pull/866 merged into maint-1.8)
This PR applies the changes of https://github.com/Toblerity/Fiona/pull/866 to maint-1.8 and resolves the found issues. 
The discovered issues are:
https://github.com/rbuffat/Fiona/blob/1ba8162137a5f6f2f9efc7997237c339c13f24a8/fiona/ogrext.pyx#L352
OGR_F_SetGeometryDirectly returns an error code when a geometry should be written for the CSV driver (the driver only supports geometries when an open parameter is set). The tests are adapted to not write features with geometries for this driver.
https://github.com/rbuffat/Fiona/blob/1ba8162137a5f6f2f9efc7997237c339 …
> Expose OGR error messages (Backport from maint-1.9)

- fiona/ogrext.pyx
- tests/test_memoryfile.py
This PR increases the coverage for MemoryFile.
Thereby I noticed the following code resulted in `BufferError: memoryview: underlying buffer is not writable`
exception. 
```
from fiona.io import MemoryFile
with MemoryFile() as memfile:
len(memfile) == 0
```
To solve this, getbuffer() is changed to return None if buffer == NULL or buffer_len == 0
> Increase coverage for MemoryFile test

- .travis.yml
Travis install  setuptools==36.0.1 in .travis.yml and then again setuptools==41.6.0 from requirements-dev.txt.
This PR changes travis.yml to use the version of setuptools from  requirements-dev.txt.
But I'm not sure if it would be better to just use: 
```
- pip install -U pip
- python -m pip install -r requirements-ci.txt
- python -m pip install -r requirements-dev.txt
```
instead of 
```
- pip install -U pip
- pip install setuptools==36.0.1
- pip install wheel
- "python -m pip install -r requirements-ci.txt"
- python -m pip wheel -r requirements-dev.txt
- python -m pip install -r requirements-dev.txt
```
> Travis install setuptools version from requirements-dev.txt

- fiona/drvsupport.py
Using the static tuple will make it so things don't have to be re-calculated each time.
> Use get_gdal_version_tuple in drvsupport

- pytest.ini
- requirements.txt
- setup.cfg
- tests/test_fio_load.py
- Add certifi to requirements
- Mark test_fio_load.py/test_creation_options with @pytest.mark.iconv
- Ignore certain warnings in the pytest warning summary
> Fix maint-1.8 appveyor

- fiona/ogrext.pyx
- tests/test_driver_options.py
Currently, Fiona does only pass options when a new layer is created, but not when a dataset is created. 
This PR passes options to gdal_create when a new dataset is created.
I'm not sure if in this case gdal_create should be wrapped with `with Env(GDAL_VALIDATE_CREATION_OPTIONS="NO")`.
This fixes https://github.com/Toblerity/Fiona/issues/968
> Pass dataset creation options to gdal_create when creating new file

- .github/workflows/rstcheck.yml
- .travis.yml
- requirements-ci.txt
Travis only caches after a successful build. I found it a bit annoying when gdal had to be compiled from source, pytest was successful but then rstcheck failed and gdal was not cached.
This PR moves the rstcheck from travis to a dedicated github action.
> Move rstcheck to a github action

- docs/cli.rst
- fiona/collection.py
- fiona/errors.py
- fiona/fio/cat.py
- fiona/ogrext.pyx
- fiona/ogrext1.pxd
- fiona/ogrext2.pxd
- fiona/ogrext3.pxd
- tests/test_collection.py
- tests/test_fio_cat.py
This PR implements a `where` argument to set an attribute filter ([where docs](https://gdal.org/user/ogr_sql_dialect.html#where), [API docs](https://gdal.org/api/vector_c_api.html#_CPPv424OGR_L_SetAttributeFilter9OGRLayerHPKc)), which could work alongside existing `bbox` and `mask` spatial filter parameters.
Basic usage is:
```python
import fiona
c = fiona.open('tests/data/coutwildrnp.shp', 'r')
print(len(list(c.items(where="WILDRNP020 BETWEEN 450 AND 480"))))  # 14
print(len(list(c.items(where="WILDRNP020 BETWEEN 450 AND 480 AND STATE='UT'"))))  # 3
print(len(list(c.items(where="STATE='UT'"))))  # 13
```
TODO/Questions:
> Add 'where' SQL clause to set attribute filter

- fiona/_transform.pyx
- tests/test_transform.py
Currently, fiona.transform does not support GeometryCollection geometries when the precision argument is set (see https://github.com/Toblerity/Fiona/issues/971). 
This PR refactors the way geometries are rounded after the transformation and supports GeometryCollection.
@sgillies I'm not sure if this is the best way to solve this issue. The code looks a bit complicated.
> Support precision for GeometryCollection geometries in fiona.transform

- fiona/ogrext.pyx
This PR fixes that a warning is raised in cases where a collection is converted to a list (https://github.com/Toblerity/Fiona/issues/986), such as:
```
with fiona.open('sample.gpkg') as src:
sample = list(src)  # issues a RuntimeWarning in fiona 1.8.18
```
However, it does not prevent that OGR_L_SetNextByIndex(start_index) is executed twice. When the start_index is 0, this is probably not a costly operation, but if the start_index is large, and the driver does not support random access, this could be costly. 
This could be solved by moving https://github.com/Toblerity/Fiona/blob/maint-1.9/fiona/ogrext.pyx#L1554-L1556 into _next() However, _next() is potentially executed many times for large datasets, thus this could generate some overhead for large datasets.
> Only warn iterator reset when iteration has started

- README.rst
- docs/manual.rst
- fiona/collection.py
- fiona/errors.py
- fiona/io.py
- tests/test_bytescollection.py
- tests/test_collection.py
- tests/test_collection_legacy.py
- tests/test_memoryfile.py
- tests/test_remove.py
Since Python 3.3,  IO and OS exceptions were re-worked as per [PEP 3151](https://www.python.org/dev/peps/pep-3151/). The new main base class is [OSError](https://docs.python.org/3/library/exceptions.html#OSError), with several other exceptions merged, including IOError (i.e. `assert IOError is OSError`).
This PR changes the old IOError alias to OSError.
> Replace IOError alias with OSError

- .github/workflows/ci_linux.yml
Fixes recent GitHub Actions error with Ubuntu:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-openssl-dev_7.58.0-2ubuntu3.15_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
> CI: run "apt-get update" before "apt-get install ..."

- tests/test_open.py
This is a "fix" for one of the CI test failures with GDAL 2.0 from #1002, with credits to @caspervdw for the [idea](https://github.com/Toblerity/Fiona/pull/1002#issuecomment-783188101).
Investigating this locally, it seems that the format is detected as "SQLite" if read from a BytesIO buffer, but the same bytes written as a file is accurately detected as "GPKG". This behavior goes away with GDAL 2.1, when both memory and file versions are detected as GPKG.
The actual issue may remain unknown, but bare in mind these are 5+ year old versions of GDAL.
> TST: require GDAL>=2.1 for test_open.py::test_write_memfile_crs_wkt

- .github/workflows/ci_linux.yml
This upgrade fixes CI failures in `tests/test_meta.py::test_print_driver_options` with a condensed traceback:
```
fiona/meta.py:146: in print_driver_options
("Dataset Creation Options", dataset_creation_options(driver)),
fiona/env.py:591: in wrapper
return f(*args, **kwds)
fiona/meta.py:82: in dataset_creation_options
return _parse_options(xml)
fiona/meta.py:41: in _parse_options
root = ET.fromstring(xml)
...
arser.feed(text)
E         File "<string>", line None
E       xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 278
```
while not investigated, it seems that one of the GDAL 3.1 patch releases fixed the bug in the XML.
> CI: upgrade GDAL 3.1.0 -> 3.1.3

- .github/workflows/ci_linux.yml
- fiona/drvsupport.py
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- setup.py
The main fix is to upgrade cython to a version that supports Python 3.10. Package classifier metadata is also updated.
Also add recent versions of GDAL and PROJ in the CI matrix.
Appyveyor (Windows) is not updated here, as it appears to have generally lagged without Python 3.9 support yet.
Closes #1043
> Add support for Python 3.10

- README.rst
This will put a green badge on README.rst for master. (It was previously set for maint-1.8, not sure if that was intentional).
> DOC: update GitHub Actions badge back to master for the master branch

- fiona/ogrext.pyx
Saw a warning when compiling about this being unreachable.
> BUG: Remove unreachable return in ogrext

- fiona/_env.pyx
- fiona/collection.py
- fiona/io.py
- fiona/logutils.py
This PR refactors `super()` to be simpler, as described by [PEP 3135](https://www.python.org/dev/peps/pep-3135/) and approved in 2007 for Python 3.0.
The "old" convention (e.g. `super(C, self)`) was only required to support Python 2.
> MAINT: use super() as described by PEP 3135

- setup.py
It is used in [`tests/test_datetime.py`](https://github.com/Toblerity/Fiona/blob/master/tests/test_datetime.py#L17).
> Add pytz to test requirements

- CHANGES.txt
- README.rst
- fiona/__init__.py
- fiona/_crs.pyx
- fiona/_transform.pyx
- fiona/collection.py
- fiona/compat.py
- fiona/crs.py
- fiona/env.py
- fiona/model.py
- fiona/ogrext.pyx
- fiona/path.py
- fiona/schema.pyx
- fiona/vfs.py
- requirements.txt
- setup.py
- tests/test_bytescollection.py
- tests/test_integration.py
- tests/test_meta.py
- tests/test_props.py
- tests/test_subtypes.py
While `six` was handy transitioning thru the Python 2 to 3 conversion, now that Fiona is fully Python 3, it is no longer needed.
Also, there are fewer instances where `fiona.compat` is needed.
> Remove 'six' module use; reduce footprint of 'fiona.compat'

- CHANGES.txt
- fiona/__init__.py
- fiona/_crs.pxd
- fiona/_crs.pyx
- fiona/_err.pyx
- fiona/collection.py
- tests/test_crs.py
- tests/test_write.py
> ENH: Add WKT format support

- fiona/_env.pyx
Closes #1091
The CA Bundle path is for wheel distributions. Since those will contain recent versions of GDAL/PROJ, this is a safe change to make.
> BUG: Set GDAL/PROJ_CURL_CA_BUNDLE environment

- MANIFEST.in
- setup.py
This should resolve #1087, where a future Python version is unable to build from a source distribution that include cythonized `*.c` and `*.cpp` files. The source distributions should only keep the source cython files, and a build should cythonize its own files.
Tested locally using `python -m build` with success. (Using Python 3.8 -- Python 3.110b1 not tested)
Other minor changes to MANIFEST.in:
- Include CITATION.txt, which was recently added
- Include pyproject.toml, which was necessary to build binary wheel
- Remove exclude MANIFEST.in, <s>as this is normally excluded</s> (update: this is [normally included](https://packaging.python.org/en/latest/guides/using-manifest-in/), so perhaps there's a good reason to leave it alone)
> BUG: force sdist to cythonize files, rather than keeping cythonized files

- .github/workflows/rstcheck.yml
For reference, the CI error was:
```
Run rstcheck -r --ignore-directives automodule --ignore-substitutions version,release,today .
rstcheck -r --ignore-directives automodule --ignore-substitutions version,release,today .
shell: /usr/bin/bash -e {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/3.8.1[2](https://github.com/Toblerity/Fiona/runs/6167026458?check_suite_focus=true#step:5:2)/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/[3](https://github.com/Toblerity/Fiona/runs/6167026458?check_suite_focus=true#step:5:3).8.12/x6[4](https://github.com/Toblerity/Fiona/runs/6167026458?check_suite_focus=true#step:5:4)/lib
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/rstcheck", line 33, in <module>
sys.exit(load_entry_point('rstcheck==3.3.1', …
```
> CI: upgrade rstcheck (and Sphinx) to resolve issue with jinja2

- pyproject.toml
Pinning the Cython version seems to break builds with future Python versions.
Leaving pinned `requirements-dev.txt` alone, as this typical from "pip freeze", and does not break sdist packages.
Closes #1087
> Unpin Cython version in pyproject.toml to support future builds

- .github/workflows/ci_linux.yml
- README.rst
- fiona/_env.pyx
- fiona/env.py
- fiona/fio/env.py
- setup.py
- tests/test_data_paths.py
> ENH: Add support for PROJ_DATA environment variable

- requirements.txt
Python 3.11 currently fails on building munch 2.3.2, while it can build newer versions of munch. By unfixing the munch version this helps Python 3.11 support
Part of #1087.
> requirements.txt: Allow munch versions >=2.3.2 to support Python 3.11

- .github/workflows/ci_linux.yml
Add a Python 3.11 job to the Linux CI.
Also updates the used actions to their latest versions.
> Linux CI: Add Python 3.11

- setup.py
Depending on `setuptools` at runtime (`install_requires` is for
specifying runtime dependencies) creates problems for external packaging
tools such as [poetry2nix](https://github.com/nix-community/poetry2nix) due to
the need to use setuptools to bootstrap package installs in nix itself.
`setuptools` is already installed by the time this line of code runs,
and isn't imported anywhere in the codebase. There should be zero change
in behavior, while allowing external packaging tools like poetry2nix to
cleanly handle Fiona.
> Remove `setuptools` as a runtime dependency

- .github/workflows/rstcheck.yml
- fiona/_env.pyx
- fiona/env.py
We're no longer doing intensive debugging of GDAL contexts, they're working, and this may expose private config options.
> Remove debug logging from _env and env

- fiona/gdal.pxi
- fiona/ogrext.pyx
- fiona/schema.pyx
- tests/test_schema.py
Closes #1140
```
fio info fio_test.geojson
{"driver": "GeoJSON", "schema": {"properties": {"time_range": "List[str]"}, ....
```
> ENH: Add support for reading string lists

- CHANGES.txt
- fiona/__init__.py
- fiona/collection.py
- fiona/env.py
- fiona/fio/env.py
- fiona/io.py
- fiona/meta.py
- fiona/session.py
- fiona/transform.py
Like rasterio. Resolves #1085.
> Remove _loading, copy into __init__

- fiona/ogrext.pyx
This PR proposes three relatively simple opportunities to speed up writes by doing less work:
1.  ogrext - performance - cache OGR field indices  (can give 2x speedup when writing layers with 400 string columns)
2.  ogrext - performance - cache OGR normalized fields (can give another ~ 10% speedup)
3.  ogrext - writerecs - remove duplicated code (minor speedup)
I had some time to look at this after noticing writes seemed very slow for layers with large number of columns (ref: https://github.com/Toblerity/Fiona/issues/1158).
all timings collected:
- using cProfile
- writing a dataset via geopandas to_file
data:
-   25,000 records
-   random point geometries
-   400 string columns, each containing random length-16 strings
| library |  version                   |  function …
> ogrext writerecords performance

- CHANGES.txt
- fiona/_geometry.pyx
- fiona/model.py
- fiona/ogrext.pyx
- fiona/transform.py
- tests/test_feature.py
- tests/test_geometry.py
- tests/test_transform.py
And add support for `__geo_interface__`.
> Undo deprecation of dicts

- CHANGES.txt
- fiona/ogrext.pyx
- tests/test_collection.py
Resolves #504 in a more general way than previously, taking care of all invalid creation options, not only `ENCODING`.
> Invalid creation options are filtered and ignored

- setup.py
`setup.py` still uses the deprecated distutils which will be removed in Python 3.12.
From [What’s New In Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated):
> The entire `distutils` package is deprecated, to be removed in Python 3.12. Its functionality for specifying package builds has already been completely replaced by third-party packages `setuptools` and `packaging`, and most other commonly used APIs are available elsewhere in the standard library (such as [platform](https://docs.python.org/3/library/platform.html#module-platform), [shutil](https://docs.python.org/3/library/shutil.html#module-shutil), [subprocess](https://docs.python.org/3/library/subprocess.html#module-subprocess) or [sysconfig](https://docs.python.org/3/library/sysconfig.html#module-sysco …
> Don't use deprecated distutils module.

- pyproject.toml
Previously, we relied on the fact that setuptools must be installed at build-time to ensure that it was also available at run-time. However, unless setuptools is explicitly listed as a run-time dependency, there's no guarantee that it won't be uninstalled. Package managers like [Spack](https://spack.io) only add run-time dependencies to `PYTHONPATH`, so this distinction becomes even more important.
I'm not sure what versions of setuptools are required, but let me know if you want me to add an upper/lower bound.
> Setuptools is required at run-time, not just build-time

- CITATION.cff
This one missed the boat for the 1.9.0 release. @sgillies could you update your how-to-release notes to update CITATION.cff?
This isn't really a big deal, it would only matter for Zenodo (which directly uses this metadata for releases). It's fine to have in the maintenance branch, and I'll cherry-pick this to the now active master branch.
> Update CITATION.cff for 1.9.0 release

- tests/test_listing.py
On the conda-forge recipe, those tests were failing because it gave a different order (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=650034&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=3626). 
I don't know if that's platform or GDAL-version dependent, but it seems OK to not rely on the exact order in the tests. 
Let me know if the PR needs to be targeted against master or maint-1.9
> TST: don't rely on exact order in listdir tests

- CHANGES.txt
- fiona/ogrext.pyx
> Log a warning message when identically named fields are found

- README.rst
Fix the badge links for the new tests and point to the maint-1.9 branch tests. 
@sgillies 
The Readme mentions `and GDAL 3.2 or higher.` but we don't test these old GDAL versions anymore in the CI. Should we update the Readme?
> Fix badge link in Readme for maint-1.9 

- docs/manual.rst
- fiona/collection.py
- fiona/model.py
- fiona/ogrext.pyx
- tests/conftest.py
- tests/test_binary_field.py
- tests/test_collection.py
- tests/test_datetime.py
- tests/test_driver_options.py
- tests/test_memoryfile.py
- tests/test_multiconxn.py
- tests/test_schema.py
- tests/test_slice.py
- tests/test_unicode.py
Since Python 3.7 (and CPython 3.6), the `dict` built-in preserves insertion order, so there is no longer any need to use OrderedDict for feature properties in Fiona.
This PR undoes 2d51d932bcab4f2b20ff4bbc7c8a802960d85c88 discussed in #57 for Fiona 1.0.1.
Closes #1094
> Change schema properties from OrderedDict back to dict built-in

- CHANGES.txt
- fiona/__init__.py
- fiona/model.py
- tests/test_model.py
Resolves #1262, which I discovered when trying to convert https://github.com/OSGeo/gdal/blob/master/autotest/ogr/data/parquet/test.parquet to GeoJSON. This bug has been lurking for a while.
@mwtoews what do you think?
@jorisvandenbossche what's the pyogrio approach to serializing bytes in GeoJSON?
> Encode bytes type feature properties using base64

- .github/workflows/tests.yaml
GDAL 3.7 was released some time ago. Let's add it to the CI and see if there is a need to change drvsupport.py.
> Add gdal 3.7 to CI

- .github/workflows/tests.yaml
- pyproject.toml
- requirements-dev.txt
Related: https://github.com/rasterio/rasterio/pull/2875
> DEP: Pin cython>=3

- tests/test_datetime.py
tzdata (2023c-8) in Debian no longer provides the US timezones:
> ```
>    * Ship only timezones in tzdata that follow the current rules of geographical
>      region (continent or ocean) and city name. Move all legacy timezone symlinks
>      (that are upgraded during package update) to tzdata-legacy. This includes
>      dropping the special handling for US/* timezones. (Closes: #1040997)
> ```
> Use America/Denver instead of US/Mountain to fix pytz.exceptions.UnknownTimeZoneError.

- docs/manual.rst
- fiona/__init__.py
There are two references to the Natural Earth datasets having Windows-1252 encoding, which are removed here since those transitioned to UTF-8 some years ago.
> Remove dated comment about Natural Earth encoding

- .github/workflows/rstcheck.yml
- .github/workflows/test_gdal_latest.yml
- .github/workflows/tests.yml
Similar to #1292 but for the `maint-1.9` branch.
> CI: upgrade actions/checkout@v3 -> v4; move GHA to .yml suffix

- fiona/__init__.py
When attempting to package a Python script using commands like `pyinstaller.exe -D --collect-all=fiona main.py`, PyInstaller includes the gdal.dll file in the main directory. This causes an issue where the '.' character representing the current directory as a parameter is passed to `os.add_dll_directory` on line 38 of the `__init__.py` file, resulting in an `OSError: [WinError 87]`.
To resolve this issue, I made a modification to 'p' by adding `os.path.abspath()` to obtain the absolute path of 'p'. This adjustment should not introduce any other errors.
> fix `OSError: [WinError 87]The parameter is incorrect. : '.' when using PyInstaller

- pyproject.toml
Since the package name is now all-lowercase, normalize the self-referential extras for consistency.
> Normalize recursive extra requirements

- .readthedocs.yaml
- environment.yml
The "API documentation" section of the online documentation uses sphinx autodoc, which requires fiona to be install in the sphinx build environment. Apparently this is needs to be done explicitly via `.readthedocs.yaml` conf file. This is what this PR does
#1306
> Attempt to fix the broken online documentation

- fiona/_env.pyx
The `CSLAddString` function takes a `char *`, not a `const char *`, which may turn into an error on new GCC. It also allocates a new array when given `NULL`, which is _copied_ by `OSRSetPROJSearchPaths`, so it is leaked.
> Fix leak in set_proj_search_path

- fiona/crs.pyx
- fiona/ogrext.pyx
The fixes 3 sets of warnings:
- An unused `__hash__` function, caused by a duplicated definition on the Cython side.
- Various `const char*` -> `char*` warnings.
- A maybe-uninitialized variable warning.
See commit message for details.
> Fix compiler warnings from extensions

- fiona/_vsiopener.pyx
This is the bare minimum needed. Parsing windows filenames as URLs is sorta broken anyway.
> Use only the urlpath parent as registry key

- CHANGES.txt
- fiona/collection.py
- fiona/ogrext.pyx
- tests/test_collection.py
> Allow a GeoJSON collection's name to be set in write mode

- CHANGES.txt
- fiona/ogrext.pyx
- fiona/schema.pyx
- tests/test_bytescollection.py
- tests/test_subtypes.py
Resolves #1321
I might like to improve how the project enumerates its data types too.
> Add an "int16" property type

- CHANGES.txt
- fiona/__init__.py
- fiona/_vsiopener.pyx
- fiona/ogrext.pyx
- tests/test_datetime.py
> Restore behavior of setting fields to values derived from date, time

- CHANGES.txt
- fiona/model.py
- tests/test_model.py
- tests/test_topojson.py
> Give model classes a nice repr again

- setup.py
logging.warn is an alias to logging.warning since Python 3.3 and will be removed in Python 3.13.
> Replace logging.warn usage with logging.warning

- CHANGES.txt
- fiona/__init__.py
- fiona/_env.pxd
- fiona/_env.pyx
- fiona/_err.pxd
- fiona/_err.pyx
- fiona/_vsiopener.pxd
- fiona/_vsiopener.pyx
- fiona/gdal.pxi
- fiona/ogrext.pyx
- tests/test_pyopener.py
Resolves #1406 by giving each `fiona.open()` collection its own VSI plugin handler when the `opener` keyword argument is used. Works with threads.
The approach is not unlike the one mentioned in https://github.com/OSGeo/gdal/pull/8772 and benefits from the `VSIRemovePluginHandler()` function added in GDAL 3.9.0. With older versions of GDAL, the Pyopener registry will accumulate openers and GDAL will accumulate plugin handlers.
This PR also adds and uses Rasterio's chaining error handler and error stack checker.
> Install new VSI plugin handler for every instance of using an opener

- CHANGES.txt
- Makefile
- fiona/_vsiopener.pyx
> Implement truncate plugin callback

- CHANGES.txt
- fiona/_vsiopener.pyx
- fiona/abc.py
- tests/test_pyopener.py
Also adds support for GDAL VSI multi-range reads. This is an attempt to take https://github.com/rasterio/rasterio/pull/3117 all the way to a stable interface and API.
`io.open()`, fsspec filesystems, and to a lesser degree, `tiledb.VFS`, are privileged openers. There are built-in adapters for these objects.
Otherwise, users should implement `fiona.abc.FileContainer` and register their class as a virtual subclass within their application like `FileContainer.register(NewClass)`.
`fiona.abc.MultiByteRangeResourceContainer` exists for completeness, to provide a template for Rasterio, and for compatibility with future GDAL/OGR drivers that may exploit it. Currently no vectors drivers do and there is no point in implementing this interface.
> Replace sketchy opener interfaces with ABCs in fiona.abc

- .github/workflows/tests.yml
Python 3.12 is faster, gives better error messages, includes more up-to-date deprecation warnings, and is now properly supported (for some time) on Conda.
> test CI: Update Conda jobs to Python 3.12

- .github/dependabot.yml
Update the Dependabot configuration to group GitHub Actions updates to a single PR, to reduce number of PRs opened.
For reference:
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
- https://learn.scientific-python.org/development/guides/gha-basic/#updating
> Dependabot: Group GitHub Actions updates to reduce number of PRs

- fiona/_geometry.pyx
Some minor improvements to help build coordinate lists a little more efficiently.
1. Lift the ndim check out of the loop. This only needs to be checked once per call.
2. Build tuples directly instead of creating a list and converting to tuples.
> Small performance improvements for GeomBuilder._buildCoords

- tests/test_pyopener.py
As with other tests that use the network.
> TST: Mark test_opener_fsspec_zip_http_fs as using the network

- docs/manual.rst
Possibly because it used to be an OrderedDict https://github.com/Toblerity/Fiona/pull/1246/files#diff-7d78d5cd5602b1e22507b370b43360c79eeec171775948ce62fa85b5a23209b8L940
> manual: use consistent dict style

- CHANGES.txt
- fiona/_transform.pyx
Very likely to fix the problem reported at https://fiona.groups.io/g/main/message/159.
> In _transform_geom() finally clean up all allocations

- fiona/model.py
- tests/test_model.py
This is a suggested fix for [Issue 1847](https://github.com/Toblerity/Fiona/issues/1487)
In cases where eq is used for an object that cannot be unpacked (i.e. is not an instance of Mapping) simply default to returning false.
Depending on style/preference, another way this could be implemented is:
```python
try:
return dict(**self) == dict(**other)
except TypeError:
return False
```
I went with the Mapping approach as it seemed to tie in more nicely with the inheritance from MutableMapping for Object, but both are pythonic and I'm happy to switch the fix over if you have a preference.
I made the assumption that the decision to do equality explicitly against the unpacked versions of the objects was in part to maintain backwards compatibility with old style Fiona representations of …
> Issue 1487 - Suggested Fix - Return false when comparing Object against values that can't be unpacked 
